sudo: false
language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
script: sbt clean coverage test
after_success:
  - sbt coverageReport coveralls
  - src/bin/publish_snapshot.sh
deploy:
  provider: script
  script: src/bin/publish_release.sh
  on:
    tags: true